export const ActionTypes = {
    ADD_SCHEDULE_REPORT: "ADD_SCHEDULE_REPORT",
    VALIDATE_FORM_VALUES: "VALIDATE_FORM_VALUES",
    ADD_TASK_ASSIGNED: "ADD_TASK_ASSIGNED",
    DEL_REPORT: "DEL_REPORT",
    DEL_TASK: "DEL_TASK"
}